apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-USERX-sr-globalbanque-com-cert
  namespace: USERX
spec:
  dnsNames:
  - tls.USERX.sr.globalbanque.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-dns
  secretName: tls-USERX-sr-globalbanque-com-cert
  usages:
  - digital signature
  - key encipherment